name: Build Weasel with Scroll Mode

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      boost_version: 1.84.0
      BOOST_ROOT: ${{ github.workspace }}\deps\boost_1_84_0
      SDKVER: 10.0.19041.0
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    
    - name: Fetch all tags
      run: git fetch --tags
    
    - name: Configure build environment
      shell: bash
      run: |
        cp env.vs2022.bat env.bat
        echo git_ref_name="$(git describe --always)" >> $GITHUB_ENV
    
    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.BOOST_ROOT }}
        key: ${{ runner.os }}-boost-${{ env.boost_version }}
    
    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      shell: bash
      run: |
        ./install_boost.bat
        ./build.bat boost arm64
    
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        sdk: ${{ env.SDKVER }}
    
    - name: Build
      run: |
        .\build.bat all
      shell: cmd
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: weasel-scroll-mode
        path: output/
